///sp keys
const KEY_CART = "KEY_CART";
const KEY_USER = "KEY_USER";
const KEY_PHONE_USER = "KEY_PHONE_USER";
const KEY_COOKIE = "KEY_COOKIE";
const KEY_OLD_USER = "KEY_OLD_USER";
const KEY_LAST_LOGIN_PHONE = "KEY_LAST_LOGIN_PHONE";
const KEY_LAST_LOGIN_EMAIL = "KEY_LAST_LOGIN_EMAIL";
const KEY_LAST_LOGIN_REGION = "KEY_LAST_LOGIN_REGION";
const KEY_SEARCH_HISTORY = "KEY_SEARCH_HISTORY";
const KEY_LAST_DIALOG_SHOWTIME = "KEY_LAST_DIALOG_SHOWTIME";

///routes argument keys
const key_categoryId = "categoryId";
const key_toCategory = "toCategory";
const key_keyWord = "keyWord";
const key_url = "url";
const key_id = "id";
const key_productType = "productType";
const key_productId = "productId";
const key_docId = "docId";
const key_docIds = "docIds";
const key_typeCode = "typeCode";
const key_title = "title";
const key_page = "page";
const key_showFeed = "showFeed";
const key_page_size = "page_size";
const key_resourcePage = "resourcePage";
const key_toDetail = "toDetail";
const key_productPrice = "productPrice";
const key_skuId = "skuId";
const key_groupIds = "groupIds";
const key_headUrl = "headUrl";
const key_shopId = "shopId";
const key_shopName = "shopName";
const key_userId = "userId";
const key_productState = "productState";
const key_productUrl = "productUrl";
const key_optionDes = "optionDes";
const key_data = "data";
const key_lock = "lock";
const key_fromRoute = "fromRoute";
const key_orderId = "orderId";
const key_default = "default";
const key_category_id = "category_id";
const key_category_ids = "category_ids";
const key_category_id_json = "category_id_json";
const key_from_count = "from_count";
const key_key_name = "key_name";
const key_sales_sort = "sales_sort";
const key_arrivals = "arrivals";
const key_p_from = "p_from";
const key_p_to = "p_to";
const key_price_sort = "price_sort";
const key_name = "name";
const key_price = "price";
const key_code = "code";
const key_count = "count";
const key_ad_type = "ad_type";
const key_type = "type";
const key_platform = "platform";
const key_special_code_json = "special_code_json";
const key_product_type = "product_type";
const key_product_id = "product_id";
const key_parent_id = "parent_id";
const key_doc_id = "doc_id";
const key_doc_ids = "doc_ids";
const key_order_no = "order_no";
const key_orderNo = "orderNo";
const key_user_id = "user_id";
const key_click_user_id = "click_user_id";
const key_category_id_to_json = "category_id_to_json";
const key_targetUserId = "targetUserId";
const key_birthday = "birthday";
const key_gender = "gender";
const key_nick = "nick";
const key_content = "content";
const key_content_id = "content_id";
const key_commentStar = "commentStar";
const key_area_city = "area_city";
const key_thumb = "thumb";
const key_thumb_url = "thumb_url";
const key_product_follow_json = "product_follow_json";
const key_option_ids_arr = "option_ids_arr";
const key_select_sku_id_list_json = "select_sku_id_list_json";
const key_sku_json = "sku_json";
const key_cart_list_json = "cart_list_json";
const key_cart_json = "cart_json";
const key_quantity = "quantity";
const key_product_option = "product_option";
const key_sku_id = "sku_id";
const key_vendor_id = "vendor_id";
const key_product_state = "product_state";
const key_product_url = "product_url";
const key_limit_quantity = "limit_quantity";
const key_product_price = "product_price";
const key_flash_time_id = "flash_time_id";
const key_stock_flag = "stock_flag";
const key_shop_id = "shop_id";
const key_login_platform = "login_platform";
const key_register_source = "register_source";
const key_device_id = "device_id";
const key_ver_code = "ver_code";
const key_region = "region";
const key_mobile = "mobile";
const key_mobile_list_to_json = "mobile_list_to_json";
const key_recipient = "recipient";
const key_address = "address";
const key_province = "province";
const key_province_id = "province_id";
const key_district = "district";
const key_district_id = "district_id";
const key_city = "city";
const key_city_id = "city_id";
const key_billing = "billing";
const key_shipping = "shipping";
const key_order_id_json = "order_id_json";
const key_order_id = "order_id";
const key_address_id = "address_id";
const key_update_type = "update_type";
const key_order_coupon_json = "order_coupon_json";
const key_order_using_allowance = "a";
const key_order_using_balance = "t";
const key_payment_type = "payment_type";
const key_payment_no = "payment_no";
const key_order_ids_json = "order_ids_json";
const key_curr_page = "curr_page";
const key_page_num = "page_num";
const key_comment_state = "comment_state";
const key_order_state_json = "order_state_json";
const key_time = "time";
const key_sign = "sign";
const key_email = "email";
const key_password = "password";
const key_old_password = "old_password";
const key_new_password = "new_password";
const key_code_result = "code_result";
const key_state_flow = "state_flow";
const key_productNum = "productNum";
const key_productName= "productName";
const key_image_json ="image_json";
const key_images ="images";
const key_mediaType ="mediaType";
const key_firstProductImageUrl ="firstProductImageUrl";
const key_reason ="reason";
const key_after_sales_no ="after_sales_no";
const key_company_name ="company_name";
const key_logistics_no ="logistics_no";
const key_content_review_to_json ="content_review_to_json";
const key_feed_comment_id ="feed_comment_id";
const key_comment_type ="comment_type";
const key_comment_json ="comment_json";
const key_remove_user_id ="remove_user_id";
const key_follow_user_id ="follow_user_id";

const key_order_source = "order_source";
const key_currency = "currency";
const key_currency_history = "currency_history";
const key_currency_symbol = "currency_symbol";

///支付方式
const String KEY_PAYMENT_PAYPAL = "paypal";
const String KEY_PAYMENT_EASYPAISA = "easypaisa";
const String KEY_PAYMENT_COD = "cod";

///原生跳转码
const int REDIRECT_CODE_PULL_NEW = 100102; //拉新页面
const int DATA_CODE_PULL_NEW = 100013;
const int REDIRECT_CODE_COMMODITY_DETAIL = 1003; //商品详情
const int REDIRECT_CODE_FLASH = 1005; //闪购列表
const int REDIRECT_CODE_HOME = 100; //首页
const int REDIRECT_CODE_CATEGORY = 101; //首页类目
const int REDIRECT_CODE_CATEGORY_LIST = 1010; //类目列表 类目id查询结果
const int categoryList = 1004; //同上 兼容老版本
const int REDIRECT_CODE_CART = 102; //首页购物车
const int REDIRECT_CODE_USER_CENTER = 103; //首页个人中心
const int REDIRECT_ADDRESS_LIST = 1038; //订地址列表
const int REDIRECT_CODE_MESSAGE_CENTER = 1024; //消息列表
const int REDIRECT_CODE_AFTER_SALE_LIST = 1025; //售后列表
const int REDIRECT_CODE_AFTER_SALE_DETAIL = 1026; //售后详情
const int REDIRECT_CODE_ORDER_DETAIL = 1027; //订单详情
