name: half_body_fox
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # dio 网络框架 このdioだ！
  dio: ^3.0.10
  #cookie 相关
  cookie_jar: ^1.0.0
  dio_cookie_manager: 1.0.0
  # 读取本地存储
  path_provider: ^1.4.4
  # sp本地缓存
  shared_preferences: ^0.5.5
  # 瀑布流
  flutter_staggered_grid_view: ^0.3.0
  # 图片加载
  cached_network_image: ^2.3.3
  # entity
  json_serializable: ^3.1.0
  # entity.g.dart 生成
  build_runner: ^1.9.0
  # ios keyChain 用于存储用户唯一标识（卸载后也不会删除）
  flutter_secure_storage: ^3.3.5
  # 跨页面事件交互
  event_bus: ^1.1.1
  # 吐司控件
  fluttertoast: ^7.1.1
  # 屏幕适配 https://www.jianshu.com/p/c762aa3882fa
  flutter_screenutil: ^3.2.0
  # 日志打印
  logger: ^0.9.4
  # 国际化 (暂时只用内部的NumberFormat)
  intl: ^0.16.1
  # 多图选择器 不能选择视频
  multi_image_picker: ^4.7.14
  # 单图片选择器
  image_picker: ^0.6.7+12
  # 图片预览
  photo_view: ^0.10.3
  # 视频播放器辅助插件
  chewie: ^0.12.0
  # 通用分享
  share: ^0.6.5+4
  # 打开外部连接
  url_launcher: ^5.7.2
  #flutter_html 富文本显示
  flutter_html: #^1.0.2
    git:
      url: https://github.com/Sub6Resources/flutter_html
      ref: dab9923ad94cff9efa08203a27d30bbb92f985f6
  # 包信息 用于获取版本号等
  package_info: ^0.4.0+11
  # 手机信息
  device_info: ^0.4.2+9
  # 下拉刷新组件
  flutter_easyrefresh: ^2.1.6
dependency_overrides:
  # For adobe_xd with Flutter 1.20.0
  video_player: ^1.0.1
  chewie: ^0.12.0

flutter:
  uses-material-design: true
